version: 2
updates:

# cargo 
- package-ecosystem: "cargo" # See documentation for possible values
    directory: "/src-tauri" # Location of package manifests
    schedule:
      interval: "weekly"

# npm
- package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
